### ISSUE TITLE
cut a release

### ISSUE THREAD

**Issue by michelleN** [deislabs/smi-sdk-go#22]
Is there anything stopping us from doing a release/tag for v1alpha1 for this sdk? do we need to define the TrafficMetrics CRD (#16) before doing a release?

cc/ @grampelberg @Pothulapati @lachie83 @slack

**Comment by Pothulapati** [comment]
I'm totally interested in doing a release. We can follow a similar structure that we did for `smi-metrics`

I don't think there's a need for TrafficMetrics CRD, like Metrics needs more like an API, that users can query and we have been doing that in `smi-metrics` repo using Kubernetes Extension APIServer. Am I missing something? O.o

**Comment by michelleN** [comment]
How do ya'll feel about a 0.1.0 release? At first, I suggested doing a 1.0.0-alpha.1 release but @lachie83 reminded me there are no great go libraries for parsing and processing things after the `-` for semantic versions. I'm thinking we do 0.x releases until all the APIs are stable and once we get to that point, we can cut a 1.0.0-beta.1 release.

What do we think? I'll go ahead and tag/cut a release once we have consensus here.

**Comment by grampelberg** [comment]
I'm behind a 0.1.0.

**Comment by Pothulapati** [comment]
Yeah, `0.1.0` would be fine I guess.

**Comment by michelleN** [comment]
great. all set. https://github.com/deislabs/smi-sdk-go/releases/tag/v0.1.0
