### ISSUE TITLE
Add Header Support for HTTPMatch?

### ISSUE THREAD

**Issue by SirNexus** [deislabs/smi-sdk-go#39]
The spec outlines that another way to define traffic (in a Traffic Spec) is through HTTP headers, which the smi sdk does not currently support. Are there plans to add this?

**Comment by grampelberg** [comment]
@SirNexus most definitely, we'd love help updating the SDK to the latest version of the spec!

**Comment by SirNexus** [comment]
Great. I can take a stab at it.

**Comment by nicholasjackson** [comment]
@SirNexus ping if you need help with the code generation, there are a few little hacks regarding namespaces with are supported in the code gen tool.

**Comment by SirNexus** [comment]
Thank you @nicholasjackson, I will let you know. I did have a clarification question though if you don't mind. The [crds](https://github.com/deislabs/smi-sdk-go/blob/master/crds/spec.yaml) in this repo define each spec as a part of `spec.smi-spec.io`, but the group version defined [here](https://github.com/deislabs/smi-sdk-go/blob/master/pkg/apis/specs/register.go) states that it should be `specs.smi-spec.io`. Is there something I don't understand about plurals here? The reason I ask is because in my testing, when using the crds generated in this repo and trying to create a listener for those custom resources, I get an error:

`no matches for kind "HTTPRouteGroup" in version "specs.smi-spec.io/v1alpha1`

Which I believe stems from the problem that we define HTTPRouteGroup as a part of `spec` and not `specs`. Is this valid? If so, I will fix in my PR.

**Comment by stefanprodan** [comment]
Thanks for the PR @SirNexus closing this!
